name: phoenix_socket
description: >-
  PhoenixSocket provides a feature-complete implementation
  of Phoenix Sockets, using a single API based on StreamChannels
  compatible with any deployment of Flutter.
version: 0.4.7
repository: https://www.github.com/matehat/phoenix-socket-dart
homepage: https://www.github.com/matehat/phoenix-socket-dart

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  equatable: ^1.2.5
  quiver: ^2.1.5
  logging: ^0.11.4
  very_good_analysis: ^1.0.3
  web_socket_channel: ^1.1.0
  rxdart: ^0.24.1

dev_dependencies:
  test: ^1.11.1
