name: phoenix_socket
description: >-
  PhoenixSocket provides a feature-complete implementation
  of Phoenix Sockets, using a single API based on StreamChannels
  compatible with any deployment of Flutter.
version: 0.0.2
homepage: https://www.github.com/matehat/phoenix-socket-dart

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  equatable: ^1.0.2
  quiver: ^2.1.2
  meta: ^1.1.8
  web_socket_channel: ^1.1.0
  pedantic: ^1.9.0

dev_dependencies:
  test: ^1.11.1
