name: phoenix_socket
description: >-
  PhoenixSocket provides a feature-complete implementation
  of Phoenix Sockets, using a single API based on StreamChannels
  compatible with any deployment of Flutter.
version: 0.4.4
homepage: https://www.github.com/matehat/phoenix-socket-dart

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  equatable: ^1.2.0
  quiver: ^2.0.0
  logging: ^0.11.4
  meta: ^1.1.8
  pedantic: ^1.8.0
  web_socket_channel: ^1.1.0
  rxdart: ^0.24.0

dev_dependencies:
  very_good_analysis: ^1.0.3
  test: ^1.11.1
